version: "3.8"

services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: events_api
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    redis:
        image: redis:7.2-alpine
        restart: always
        ports:
            - "6379:6379"
        command: ["redis-server", "--requirepass", ""]
        volumes:
            - redis_data:/data

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - mysql

volumes:
    mysql_data:
    redis_data:
